#name: Daily Model Evaluation
#on:
#  schedule:
#    # Spustit každý den v 06:00 ráno (kdy už jsou data z yfinance určitě hotová)
#    - cron: '0 6 * * *'
#jobs:
#  evaluate:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Run Evaluation ETL
#        env:
#          DB_URL: ${{ secrets.DB_URL }}
#        run: |
#          # TODO localni requirements jen pro ty 2 scripty nejak udelat
#          pip install -r requirements.txt
#          python scripts/evaluate_performance.py
#
#          # TODO
#          python scripts/predict_nasdaq_100.py
